-- Full description - describe the table books without using DESCRIBE OR EXPLAIN commands
SELECT
	COLUMN_NAME,
	COLUMN_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
	IS_NULLABLE,
	COLUMN_DEFAULT,
	COLUMN_KEY,
	EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = "alx_book_store"
	AND TABLE_NAME = 'books'
ORDER BY ORDINAL_POSITION;
